using System;

class control
{
    static void Main()
    {

        /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

        bool yolo = true;
        uint term1, term2, term3, sum;
        sum = 2;
        term1 = 1;
        term2 = 2;
        term3 = 0;
        uint size = 4000000;
        while (yolo)
        {
            if (term3 > size || term2 > size || term1 > size) { break; }
            if (term3 % 2 == 0)
            {
                sum += term3;
            }
            term3 = term1 + term2;
            term1 = term2;
            term2 = term3;
        }
        Console.WriteLine(sum);
        Console.WriteLine("Press any key to continue...");
        Console.ReadKey();
    }
}

