using System;

class control {
    static void Main() { 
        
        /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

        /* This is and incomplete project and will not be completed untill i recover the finished file */
        int x, y, z;
        int x = 1;
        int y = 2;
        int z = 3;

        x = x + y;
        Console.WriteLine(x);
        Console.WriteLine(y);
        Console.WriteLine("Press any key to continue...");
        Console.ReadKey();
    }
}
